# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='risk.scoring_card',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x11risk.scoring_card\"(\n\x0bModelParams\x12\x19\n\x11scoring_card_name\x18\x01 \x01(\t\"m\n\nModelInput\x12;\n\x0f\x61ttributes_list\x18\x01 \x03(\x0b\x32\".risk.scoring_card.ModelInput.Pair\x1a\"\n\x04Pair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')
)




_MODELPARAMS = _descriptor.Descriptor(
  name='ModelParams',
  full_name='risk.scoring_card.ModelParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scoring_card_name', full_name='risk.scoring_card.ModelParams.scoring_card_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=72,
)


_MODELINPUT_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='risk.scoring_card.ModelInput.Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='risk.scoring_card.ModelInput.Pair.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='risk.scoring_card.ModelInput.Pair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=183,
)

_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='risk.scoring_card.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attributes_list', full_name='risk.scoring_card.ModelInput.attributes_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MODELINPUT_PAIR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=183,
)

_MODELINPUT_PAIR.containing_type = _MODELINPUT
_MODELINPUT.fields_by_name['attributes_list'].message_type = _MODELINPUT_PAIR
DESCRIPTOR.message_types_by_name['ModelParams'] = _MODELPARAMS
DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelParams = _reflection.GeneratedProtocolMessageType('ModelParams', (_message.Message,), dict(
  DESCRIPTOR = _MODELPARAMS,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:risk.scoring_card.ModelParams)
  ))
_sym_db.RegisterMessage(ModelParams)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), dict(

  Pair = _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), dict(
    DESCRIPTOR = _MODELINPUT_PAIR,
    __module__ = 'api_pb2'
    # @@protoc_insertion_point(class_scope:risk.scoring_card.ModelInput.Pair)
    ))
  ,
  DESCRIPTOR = _MODELINPUT,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:risk.scoring_card.ModelInput)
  ))
_sym_db.RegisterMessage(ModelInput)
_sym_db.RegisterMessage(ModelInput.Pair)


# @@protoc_insertion_point(module_scope)
