# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/div/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='models/div/api.proto',
  package='risk.div_model',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14models/div/api.proto\x12\x0erisk.div_model\"/\n\nModelInput\x12\x10\n\x08\x64ividend\x18\x01 \x01(\x01\x12\x0f\n\x07\x64ivisor\x18\x02 \x01(\x01\x62\x06proto3')
)




_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='risk.div_model.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dividend', full_name='risk.div_model.ModelInput.dividend', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='divisor', full_name='risk.div_model.ModelInput.divisor', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), dict(
  DESCRIPTOR = _MODELINPUT,
  __module__ = 'models.div.api_pb2'
  # @@protoc_insertion_point(class_scope:risk.div_model.ModelInput)
  ))
_sym_db.RegisterMessage(ModelInput)


# @@protoc_insertion_point(module_scope)
