# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='risk.scoring_to_pd_src',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x16risk.scoring_to_pd_src\"+\n\x0bModelParams\x12\x1c\n\x14reference_scale_name\x18\x01 \x01(\t\"\x1b\n\nModelInput\x12\r\n\x05score\x18\x01 \x01(\x02\x62\x06proto3')
)




_MODELPARAMS = _descriptor.Descriptor(
  name='ModelParams',
  full_name='risk.scoring_to_pd_src.ModelParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reference_scale_name', full_name='risk.scoring_to_pd_src.ModelParams.reference_scale_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=80,
)


_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='risk.scoring_to_pd_src.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='risk.scoring_to_pd_src.ModelInput.score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['ModelParams'] = _MODELPARAMS
DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelParams = _reflection.GeneratedProtocolMessageType('ModelParams', (_message.Message,), dict(
  DESCRIPTOR = _MODELPARAMS,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:risk.scoring_to_pd_src.ModelParams)
  ))
_sym_db.RegisterMessage(ModelParams)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), dict(
  DESCRIPTOR = _MODELINPUT,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:risk.scoring_to_pd_src.ModelInput)
  ))
_sym_db.RegisterMessage(ModelInput)


# @@protoc_insertion_point(module_scope)
