FROM envoyproxy/envoy

RUN apt-get update
RUN apt-get -y install python3 python3-pip curl
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools

COPY ./service /app
COPY ./client_sync.py /app
COPY ./client_async.py /app
COPY ./service/service-envoy.yaml /etc/service-envoy.yaml
WORKDIR /app
RUN pip3 install --no-cache-dir -r requirements.txt
RUN python3 codegen.py

RUN chmod u+x /app/start_service.sh
ENTRYPOINT /app/start_service.sh
