# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: risk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='risk.proto',
  package='risk',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nrisk.proto\x12\x04risk\"W\n\x12\x43\x61lculationRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x18\n\x10model_parameters\x18\x02 \x01(\x0c\x12\x13\n\x0bmodel_input\x18\x03 \x01(\x0c\"{\n\x13\x43\x61lculationResponse\x12\x35\n\x06values\x18\x01 \x03(\x0b\x32%.risk.CalculationResponse.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32P\n\nRiskEngine\x12\x42\n\tCalculate\x12\x18.risk.CalculationRequest\x1a\x19.risk.CalculationResponse\"\x00\x62\x06proto3')
)




_CALCULATIONREQUEST = _descriptor.Descriptor(
  name='CalculationRequest',
  full_name='risk.CalculationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='risk.CalculationRequest.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_parameters', full_name='risk.CalculationRequest.model_parameters', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_input', full_name='risk.CalculationRequest.model_input', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=107,
)


_CALCULATIONRESPONSE_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='risk.CalculationResponse.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='risk.CalculationResponse.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='risk.CalculationResponse.ValuesEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=232,
)

_CALCULATIONRESPONSE = _descriptor.Descriptor(
  name='CalculationResponse',
  full_name='risk.CalculationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='risk.CalculationResponse.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CALCULATIONRESPONSE_VALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=232,
)

_CALCULATIONRESPONSE_VALUESENTRY.containing_type = _CALCULATIONRESPONSE
_CALCULATIONRESPONSE.fields_by_name['values'].message_type = _CALCULATIONRESPONSE_VALUESENTRY
DESCRIPTOR.message_types_by_name['CalculationRequest'] = _CALCULATIONREQUEST
DESCRIPTOR.message_types_by_name['CalculationResponse'] = _CALCULATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculationRequest = _reflection.GeneratedProtocolMessageType('CalculationRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATIONREQUEST,
  __module__ = 'risk_pb2'
  # @@protoc_insertion_point(class_scope:risk.CalculationRequest)
  ))
_sym_db.RegisterMessage(CalculationRequest)

CalculationResponse = _reflection.GeneratedProtocolMessageType('CalculationResponse', (_message.Message,), dict(

  ValuesEntry = _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), dict(
    DESCRIPTOR = _CALCULATIONRESPONSE_VALUESENTRY,
    __module__ = 'risk_pb2'
    # @@protoc_insertion_point(class_scope:risk.CalculationResponse.ValuesEntry)
    ))
  ,
  DESCRIPTOR = _CALCULATIONRESPONSE,
  __module__ = 'risk_pb2'
  # @@protoc_insertion_point(class_scope:risk.CalculationResponse)
  ))
_sym_db.RegisterMessage(CalculationResponse)
_sym_db.RegisterMessage(CalculationResponse.ValuesEntry)


_CALCULATIONRESPONSE_VALUESENTRY._options = None

_RISKENGINE = _descriptor.ServiceDescriptor(
  name='RiskEngine',
  full_name='risk.RiskEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=234,
  serialized_end=314,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calculate',
    full_name='risk.RiskEngine.Calculate',
    index=0,
    containing_service=None,
    input_type=_CALCULATIONREQUEST,
    output_type=_CALCULATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RISKENGINE)

DESCRIPTOR.services_by_name['RiskEngine'] = _RISKENGINE

# @@protoc_insertion_point(module_scope)
