# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import risk_pb2 as risk__pb2


class RiskEngineStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Calculate = channel.unary_unary(
        '/risk.RiskEngine/Calculate',
        request_serializer=risk__pb2.CalculationRequest.SerializeToString,
        response_deserializer=risk__pb2.CalculationResponse.FromString,
        )


class RiskEngineServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Calculate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RiskEngineServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Calculate': grpc.unary_unary_rpc_method_handler(
          servicer.Calculate,
          request_deserializer=risk__pb2.CalculationRequest.FromString,
          response_serializer=risk__pb2.CalculationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'risk.RiskEngine', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
