# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/avg/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='models/avg/api.proto',
  package='risk.avg_model',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14models/avg/api.proto\x12\x0erisk.avg_model\"r\n\x0bModelParams\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.risk.avg_model.ModelParams.AverageType\",\n\x0b\x41verageType\x12\x0e\n\nARITHMETIC\x10\x00\x12\r\n\tGEOMETRIC\x10\x01\"\x1c\n\nModelInput\x12\x0e\n\x06values\x18\x01 \x03(\x01\x62\x06proto3')
)



_MODELPARAMS_AVERAGETYPE = _descriptor.EnumDescriptor(
  name='AverageType',
  full_name='risk.avg_model.ModelParams.AverageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARITHMETIC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEOMETRIC', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=110,
  serialized_end=154,
)
_sym_db.RegisterEnumDescriptor(_MODELPARAMS_AVERAGETYPE)


_MODELPARAMS = _descriptor.Descriptor(
  name='ModelParams',
  full_name='risk.avg_model.ModelParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='risk.avg_model.ModelParams.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELPARAMS_AVERAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=154,
)


_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='risk.avg_model.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='risk.avg_model.ModelInput.values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=184,
)

_MODELPARAMS.fields_by_name['type'].enum_type = _MODELPARAMS_AVERAGETYPE
_MODELPARAMS_AVERAGETYPE.containing_type = _MODELPARAMS
DESCRIPTOR.message_types_by_name['ModelParams'] = _MODELPARAMS
DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelParams = _reflection.GeneratedProtocolMessageType('ModelParams', (_message.Message,), dict(
  DESCRIPTOR = _MODELPARAMS,
  __module__ = 'models.avg.api_pb2'
  # @@protoc_insertion_point(class_scope:risk.avg_model.ModelParams)
  ))
_sym_db.RegisterMessage(ModelParams)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), dict(
  DESCRIPTOR = _MODELINPUT,
  __module__ = 'models.avg.api_pb2'
  # @@protoc_insertion_point(class_scope:risk.avg_model.ModelInput)
  ))
_sym_db.RegisterMessage(ModelInput)


# @@protoc_insertion_point(module_scope)
