# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='risk.portfolio_optimization',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x1brisk.portfolio_optimization\"\xbf\x02\n\x0bModelParams\x12G\n\x04type\x18\x01 \x01(\x0e\x32\x39.risk.portfolio_optimization.ModelParams.MinimizationType\x12Q\n\talgorithm\x18\x02 \x01(\x0e\x32>.risk.portfolio_optimization.ModelParams.MinimizationAlgorithm\x12\x18\n\x10number_of_assets\x18\x03 \x01(\r\"8\n\x10MinimizationType\x12\x0c\n\x08VARIANCE\x10\x00\x12\x16\n\x12RETURN_TO_SD_RATIO\x10\x01\"@\n\x15MinimizationAlgorithm\x12\x10\n\x0cTRUST_CONSTR\x10\x00\x12\t\n\x05SLSQP\x10\x01\x12\n\n\x06\x43OBYLA\x10\x02\"\xe4\x01\n\nModelInput\x12\x11\n\tvariances\x18\x01 \x03(\x01\x12\x0f\n\x07returns\x18\x02 \x03(\x01\x12R\n\x16\x61\x64\x64itional_constraints\x18\x03 \x03(\x0b\x32\x32.risk.portfolio_optimization.ModelInput.Constraint\x1a^\n\nConstraint\x12\x14\n\x0cweight_index\x18\x01 \x01(\r\x12\x1c\n\x14interval_lower_bound\x18\x02 \x01(\x01\x12\x1c\n\x14interval_upper_bound\x18\x03 \x01(\x01\x62\x06proto3')
)



_MODELPARAMS_MINIMIZATIONTYPE = _descriptor.EnumDescriptor(
  name='MinimizationType',
  full_name='risk.portfolio_optimization.ModelParams.MinimizationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VARIANCE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETURN_TO_SD_RATIO', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=240,
  serialized_end=296,
)
_sym_db.RegisterEnumDescriptor(_MODELPARAMS_MINIMIZATIONTYPE)

_MODELPARAMS_MINIMIZATIONALGORITHM = _descriptor.EnumDescriptor(
  name='MinimizationAlgorithm',
  full_name='risk.portfolio_optimization.ModelParams.MinimizationAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRUST_CONSTR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLSQP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COBYLA', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=298,
  serialized_end=362,
)
_sym_db.RegisterEnumDescriptor(_MODELPARAMS_MINIMIZATIONALGORITHM)


_MODELPARAMS = _descriptor.Descriptor(
  name='ModelParams',
  full_name='risk.portfolio_optimization.ModelParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='risk.portfolio_optimization.ModelParams.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='risk.portfolio_optimization.ModelParams.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_assets', full_name='risk.portfolio_optimization.ModelParams.number_of_assets', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELPARAMS_MINIMIZATIONTYPE,
    _MODELPARAMS_MINIMIZATIONALGORITHM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=362,
)


_MODELINPUT_CONSTRAINT = _descriptor.Descriptor(
  name='Constraint',
  full_name='risk.portfolio_optimization.ModelInput.Constraint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight_index', full_name='risk.portfolio_optimization.ModelInput.Constraint.weight_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval_lower_bound', full_name='risk.portfolio_optimization.ModelInput.Constraint.interval_lower_bound', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval_upper_bound', full_name='risk.portfolio_optimization.ModelInput.Constraint.interval_upper_bound', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=593,
)

_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='risk.portfolio_optimization.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variances', full_name='risk.portfolio_optimization.ModelInput.variances', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returns', full_name='risk.portfolio_optimization.ModelInput.returns', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additional_constraints', full_name='risk.portfolio_optimization.ModelInput.additional_constraints', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MODELINPUT_CONSTRAINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=593,
)

_MODELPARAMS.fields_by_name['type'].enum_type = _MODELPARAMS_MINIMIZATIONTYPE
_MODELPARAMS.fields_by_name['algorithm'].enum_type = _MODELPARAMS_MINIMIZATIONALGORITHM
_MODELPARAMS_MINIMIZATIONTYPE.containing_type = _MODELPARAMS
_MODELPARAMS_MINIMIZATIONALGORITHM.containing_type = _MODELPARAMS
_MODELINPUT_CONSTRAINT.containing_type = _MODELINPUT
_MODELINPUT.fields_by_name['additional_constraints'].message_type = _MODELINPUT_CONSTRAINT
DESCRIPTOR.message_types_by_name['ModelParams'] = _MODELPARAMS
DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelParams = _reflection.GeneratedProtocolMessageType('ModelParams', (_message.Message,), dict(
  DESCRIPTOR = _MODELPARAMS,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:risk.portfolio_optimization.ModelParams)
  ))
_sym_db.RegisterMessage(ModelParams)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), dict(

  Constraint = _reflection.GeneratedProtocolMessageType('Constraint', (_message.Message,), dict(
    DESCRIPTOR = _MODELINPUT_CONSTRAINT,
    __module__ = 'api_pb2'
    # @@protoc_insertion_point(class_scope:risk.portfolio_optimization.ModelInput.Constraint)
    ))
  ,
  DESCRIPTOR = _MODELINPUT,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:risk.portfolio_optimization.ModelInput)
  ))
_sym_db.RegisterMessage(ModelInput)
_sym_db.RegisterMessage(ModelInput.Constraint)


# @@protoc_insertion_point(module_scope)
