# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='risk.portfolio_var',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x12risk.portfolio_var\"P\n\x0bModelParams\x12\x18\n\x10number_of_assets\x18\x01 \x01(\r\x12\r\n\x05\x61lpha\x18\x02 \x01(\x01\x12\x18\n\x10time_perspective\x18\x03 \x01(\r\"9\n\nModelInput\x12\x14\n\x0c\x61sset_prices\x18\x01 \x03(\x01\x12\x15\n\rasset_weights\x18\x02 \x03(\x01\x62\x06proto3')
)




_MODELPARAMS = _descriptor.Descriptor(
  name='ModelParams',
  full_name='risk.portfolio_var.ModelParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_assets', full_name='risk.portfolio_var.ModelParams.number_of_assets', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='risk.portfolio_var.ModelParams.alpha', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_perspective', full_name='risk.portfolio_var.ModelParams.time_perspective', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=113,
)


_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='risk.portfolio_var.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset_prices', full_name='risk.portfolio_var.ModelInput.asset_prices', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_weights', full_name='risk.portfolio_var.ModelInput.asset_weights', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['ModelParams'] = _MODELPARAMS
DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelParams = _reflection.GeneratedProtocolMessageType('ModelParams', (_message.Message,), dict(
  DESCRIPTOR = _MODELPARAMS,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:risk.portfolio_var.ModelParams)
  ))
_sym_db.RegisterMessage(ModelParams)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), dict(
  DESCRIPTOR = _MODELINPUT,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:risk.portfolio_var.ModelInput)
  ))
_sym_db.RegisterMessage(ModelInput)


# @@protoc_insertion_point(module_scope)
