# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/sum/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='models/sum/api.proto',
  package='risk.sum_model',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14models/sum/api.proto\x12\x0erisk.sum_model\"\x1c\n\nModelInput\x12\x0e\n\x06values\x18\x01 \x03(\x01\x62\x06proto3')
)




_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='risk.sum_model.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='risk.sum_model.ModelInput.values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), dict(
  DESCRIPTOR = _MODELINPUT,
  __module__ = 'models.sum.api_pb2'
  # @@protoc_insertion_point(class_scope:risk.sum_model.ModelInput)
  ))
_sym_db.RegisterMessage(ModelInput)


# @@protoc_insertion_point(module_scope)
